"APIs":
  - changed-files:
      - any-glob-to-any-file: inc/**/*

"binding":
  - changed-files:
      - any-glob-to-any-file: src/bindings/**/*

"documentation":
  - changed-files:
      - any-glob-to-any-file: README.md

"font":
  - changed-files:
      - any-glob-to-any-file: src/loaders/sfnt/**/*

"image":
  - changed-files:
      - any-glob-to-any-file:
          - src/loaders/jpg/**/*
          - src/loaders/external_jpg/**/*
          - src/loaders/png/**/*
          - src/loaders/external_png/**/*
          - src/loaders/webp/**/*
          - src/loaders/external_webp/**/*
          - src/loaders/raw/**/*
          - src/savers/gif/**/*

"svg":
  - changed-files:
      - any-glob-to-any-file: src/loaders/svg/**/*

"media":
  - changed-files:
      - any-glob-to-any-file: src/loaders/media/**/*

"test":
  - changed-files:
      - any-glob-to-any-file: test/**/*

"infrastructure":
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
          - meson.build
          - meson_option.txt

"lottie":
  - changed-files:
      - any-glob-to-any-file: src/loaders/lottie/**/*

"cpu":
  - changed-files:
      - any-glob-to-any-file: src/renderer/cpu_engine/**/*

"webgpu":
  - changed-files:
      - any-glob-to-any-file:
          - src/renderer/gpu_engine/wg/**/*
          - src/renderer/gpu_engine/*

"gl":
  - changed-files:
      - any-glob-to-any-file:
          - src/renderer/gpu_engine/gl/**/*
          - src/renderer/gpu_engine/*

"renderer":
  - changed-files:
      - any-glob-to-any-file:
          - src/renderer/*
          - src/common/**/*
