"APIs":
  - changed-files:
      - any-glob-to-any-file: inc/**/*

"binding":
  - changed-files:
      - any-glob-to-any-file: src/bindings/**/*

"documentation":
  - changed-files:
      - any-glob-to-any-file: README.md

"font":
  - changed-files:
      - any-glob-to-any-file: src/modules/sfnt/load/**/*

"image":
  - changed-files:
      - any-glob-to-any-file:
          - src/modules/jpg/load/internal/**/*
          - src/modules/jpg/load/external/**/*
          - src/modules/png/load/internal/**/*
          - src/modules/png/load/external/**/*
          - src/modules/webp/load/internal/**/*
          - src/modules/webp/load/external/**/*
          - src/modules/raw/load/**/*
          - src/modules/gif/save/**/*

"svg":
  - changed-files:
      - any-glob-to-any-file: src/modules/svg/load/**/*

"media":
  - changed-files:
      - any-glob-to-any-file: src/modules/media/load/**/*

"test":
  - changed-files:
      - any-glob-to-any-file: test/**/*

"infrastructure":
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
          - meson.build
          - meson_option.txt

"lottie":
  - changed-files:
      - any-glob-to-any-file: src/modules/lottie/load/**/*

"cpu":
  - changed-files:
      - any-glob-to-any-file: src/renderer/cpu_engine/**/*

"webgpu":
  - changed-files:
      - any-glob-to-any-file:
          - src/renderer/gpu_engine/wg/**/*
          - src/renderer/gpu_engine/*

"gl":
  - changed-files:
      - any-glob-to-any-file:
          - src/renderer/gpu_engine/gl/**/*
          - src/renderer/gpu_engine/*

"renderer":
  - changed-files:
      - any-glob-to-any-file:
          - src/renderer/*
          - src/common/**/*
