#pragma once

#define THORVG_LOTTIE_LOADER_SUPPORT 1

#define THORVG_SVG_LOADER_SUPPORT 1

#define THORVG_SW_RASTER_SUPPORT 1

#define THORVG_TVG_LOADER_SUPPORT 1

#define THORVG_VERSION_STRING "0.13.99"
